title: 'Embedded Rocks!'
description: DIY electronics, innovative embedded systems, and open-source projects—all under one roof
show_downloads: false
github:
  is_project_page: false
logo: /assets/img/logo.png
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
